name: Build

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.5

    steps:
      - uses: actions/checkout@v2

      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: 'documentation/source/swagger/*.yaml'
