on:
  push:
    branches: [ master ]
    tags:
      - v1.*

name: Create Slate Documentation on Push

jobs:
  action-filter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
        uses: docker://decathlon/slate-builder-action:2.0.0
        env:
          DOC_BASE_FOLDER: docs/
          ZIP_BUILD: false
      - name: Deploy to GitHub Pages
        uses: docker://maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs/build/
