on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '**'

name: Validate

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation

    strategy:
      matrix:
        ruby-version: [3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install -g @apidevtools/swagger-cli

      - run: swagger-cli validate source/swagger/open_admin_metrics.yaml
      - run: swagger-cli validate source/swagger/open_data_status_outage.yaml

      # Fase 1
      - run: swagger-cli validate source/swagger/open_data_channels.yaml
      - run: swagger-cli validate source/swagger/open_life_welfare.yaml
      - run: swagger-cli validate source/swagger/open_people.yaml
      - run: swagger-cli validate source/swagger/open_price_linked_bonds.yaml
      - run: swagger-cli validate source/swagger/open_residence.yaml
      - run: swagger-cli validate source/swagger/open_vehicle.yaml
      - run: swagger-cli validate source/swagger/open_welfare.yaml

      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: 'source/swagger/*.yaml'
